os:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  toolset: v90
  zip_name: itkBullseye_%APPVEYOR_REPO_TAG_NAME%_windows_%PLATFORM%_%toolset%
  testing: ON

install:
  - git submodule update --init --recursive
  - cd %APPVEYOR_BUILD_FOLDER%\thirdParty\googletest
  - git checkout -b release-1.4.0 origin\release-1.4.0

platform:
  - Win32
  # - x64

configuration:
  - Release

before_build:
  - echo %PLATFORM%
  - echo %configuration%
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - if "%PLATFORM%" == "x64" (
      curl -L http://mrkonrad.github.io/MRKonrad/files/ITK_built/ITK412_win_%PLATFORM%_install.zip -o itk_install.zip &&
      7z x -r itk_install.zip
    )
  - if "%PLATFORM%" == "Win32" (
      mkdir ITK_install &&
      cd ITK_install &&
      curl -L https://github.com/MRKonrad/build-itk/releases/download/1.0.4/itk_v4.13.2_windows_Win32_v90.zip -o itk_install.zip &&
      7z x -r itk_install.zip &&
      cd ..
    )
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -Bbin -A%PLATFORM% -T%toolset% -DCMAKE_INSTALL_PREFIX=install -DITK_DIR_HINTS="../ITK_install" -DitkBullseye_BUILD_TESTING=%testing%

build:
  project: bin\itkBullseye.sln  # path to Visual Studio solution or project
  parallel: true           # enable MSBuild parallel builds
  verbosity: normal        # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  # install the files
  - cd %APPVEYOR_BUILD_FOLDER%\bin
  - dir
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  - dir %CONFIGURATION%
  - cd ..
  - dir install
  - cd install
  - 7z a %zip_name%.zip * -r # zip
  - cd ..
  - mkdir deployment
  - copy install\%zip_name%.zip deployment\%zip_name%.zip
  - dir
  - dir deployment

test_script:
  - if "%testing%" == "ON" (
      cd %APPVEYOR_BUILD_FOLDER%\bin\tests\%CONFIGURATION% &&
      itkBullseyeTests.exe
    )

artifacts:
  - path: deployment\*.*

deploy:
  provider: GitHub
  auth_token:
    secure: J21nvYa1j0K5KlxFo+HRmHh7usNai+gOoSjwYFCbYuVfip3buosHdN99ltY677MY
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    configuration: Release
