language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - exe_extended_name: itkBullseye_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}

install:
  # download ITK
  - cd ${TRAVIS_BUILD_DIR}/..
  - curl -L -O http://mrkonrad.github.io/MRKonrad/files/ITK_built/ITK413_${TRAVIS_OS_NAME}_install.zip
  - unzip -a -q ITK413_${TRAVIS_OS_NAME}_install.zip
  - cd ${TRAVIS_BUILD_DIR}/thirdParty/googletest

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -Bbin -DITK_DIR_HINTS="../ITK_install" -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/bin/install
  - cmake --build bin --config RELEASE --target itkBullseyeTests
  - cd bin/tests
  - ./itkBullseyeTests

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --build bin --config RELEASE --target install
  - cd ${TRAVIS_BUILD_DIR}/bin/install
  - zip -r ${exe_extended_name}.zip *
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment
  - cp ${TRAVIS_BUILD_DIR}/bin/install/${exe_extended_name}.zip ${TRAVIS_BUILD_DIR}/deployment/${exe_extended_name}.zip
  - ls ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}/deployment

deploy:
  provider: releases # GitHub
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: ON
    condition: ${CXX} == "g++" # I guess I have to pick one compiler

notifications:
  slack:
    rooms:
      - secure: F+gw+WmGh/tQ0E6bFNecmD3PGcp4pqbAMjR0MZhDK53A+ayVTqRqwni35vJ0MTvBViI3ga2Nqawtw/hcV7hON+yl9Knp28ntYHHhIA2znuD6r+pfxCrgovfztV5h6u0aBVZWrIm/uiOZ6cIraL3c9dnTC0aWqV/LvsV+TtgDfpRKzFQD3tzj+6qEnh76yPLy1m5buVE+ZxsC+mSF4aiV42EWSO+Oi8x+ihkgX82QVMuPF8B1xkmYJsjL9NZaw0P8FqDpbZRI9NMLrg8K/M2uCKaFZuaeqFmTuQQ8tYQsNTR+KsmF61w9tbr2UdOR6VNmFKZfXDTCGJy9qe2OQLY/2qnYnBhJLNhxn6ZCPmmhSByb/B/yDiDvgM4k4miqIFeekNEb/+2My27bgosQu3mqSCymZkfS00YNlZthJUIv/zu31EOw8ZPAq5BBWC/YbohemUIdk0sZb/r7d+EVEMyhz/OqYlEJIXAVoHO/JMh1Z9o+ofG8oiHWqfiShqZxbsW08g81z9cIIPaQ4pqmFeLiRvLzbE4gE3WLWpZ9SRpfAdhXuSHSvTw9+pRDkInlPNWH3SzuhBf4gIl6ApEdntjam+vRRi6ODazS5cXvHFh+9EE6h0xzQAFwYwwJVA8WQZZvqO1To7Gip3wUuqR0XCH2yOaEvOPNJcd1wxCOlGBb/Eo=
    on_success: always
