//
// Created by Konrad Werys on 10/05/2019.
//

#ifndef ITKBULLSEYE_ITKBULLSEYELIB_EXPORT_H
#define ITKBULLSEYE_ITKBULLSEYELIB_EXPORT_H

#ifndef ITKBULLSEYELIB_EXPORT
#define ITKBULLSEYELIB_EXPORT
#endif

#ifndef ITKBULLSEYELIB_COMPILED
#define ITKBULLSEYELIB_COMPILED
#endif

#endif //ITKBULLSEYE_ITKBULLSEYELIB_EXPORT_H
